### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by davidseward-dev** [airbrake/airbrake-cli#4]
Hi, I'm following the documentation at https://airbrake.io/docs/airbrake-cli/ and wanted to try out sourcemaps.  I'm entering:

```
airbrake sourcemaps create --project-id 123 --from-file 'dist/js/app.123.js.map' --name 'app.123.js.map' --pattern 'app.%.js'
```

But I'm seeing: 

```
Error: unknown command "sourcemaps" for "airbrake"
```

airbrake version 1.0.2
installed via homebrew

**Comment by scottsbaldwin** [comment]
@thompiler can you take a look at this one?

**Comment by thompiler** [comment]
>@thompiler can you take a look at this one?

Yup, I will take a look. 👍

**Comment by davidseward-dev** [comment]
Thank you!  Let me know if you need any other info from me

**Comment by sgray** [comment]
Hi, @ds-combine-ai. Thanks for letting us know. I've cut a new release that includes the `sourcemaps` command. After upgrading via brew, you should be all set.

**Comment by davidseward-dev** [comment]
Awesome, thanks for the fast turnaround.  Have got the new version and can see `sourcemaps` in there.

**Comment by thompiler** [comment]
>Hi, @ds-combine-ai. Thanks for letting us know. I've cut a new release that includes the `sourcemaps` command. After upgrading via brew, you should be all set.

Thanks @sgray! 👍
