### ISSUE TITLE
REFUSED_STREAM when trying to upload sourcemaps

### ISSUE THREAD

**Issue by davidseward-dev** [airbrake/airbrake-cli#5]
Hey, I've just started seeing this issue when uploading sourcemaps using the cli.  I did an upgrade to the latest version to double check, but I still see the error:

```
Post "https://api.airbrake.io/api/v4/projects/xxxxxx/sourcemaps?key=xxxxxxxx": http2: Transport: cannot retry err [stream error: stream ID 1; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error
2022/08/18 15:59:43 io: read/write on closed pipe
Error: Post "https://api.airbrake.io/api/v4/projects/xxxxxx/sourcemaps?key=xxxxxxxx": http2: Transport: cannot retry err [stream error: stream ID 1; REFUSED_STREAM; received from peer] after Request.Body was written; define Request.GetBody to avoid this error
```
```
airbrake -v
airbrake version 1.2.9
```

Am I doing something wrong?

**Comment by kyrylo** [comment]
Does this occur consistently?

**Comment by davidseward-dev** [comment]
Thanks for your quick respons @kyrylo.  Yes it was happening consistently last night, and I tried again this morning with the same result.  This is the command that fails:

`airbrake sourcemaps create --project-id 123456 --from-file app_from_file --name app_name`

We have this in a shell script that we run after deploys, and our script hasn't changed at all.

**Comment by davidseward-dev** [comment]
I'm still getting the issue when doing our latest deployment today.

**Comment by kyrylo** [comment]
We are looking into this. This is likely an issue with our backend, not airbrake-cli.

**Comment by davidseward-dev** [comment]
Thanks for looking into it @kyrylo 👍 Did you find anything?

**Comment by kyrylo** [comment]
Should be fixed. Can you confirm?

**Comment by davidseward-dev** [comment]
Yes, it's working again now - thank you @kyrylo 🙇 .  Closing this one down.
